services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgres
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - POSTGRES_URI=postgresql://user:password@postgres:5432/food_db

volumes:
  mongodb_data:
  postgres_data: